name: Auto Approve PRs

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        uses: dkhmelenko/autoapproval@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from_owner: Law78
          # Opzionale: specifica criteri di approvazione
          # required-labels: 'auto-approve'  # Esempio di etichetta necessaria
          # ignore-labels: 'do-not-approve'  # Esempio di etichetta da ignorare
