name: Azure Deploy

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: "An example input"
        required: true
        default: "test"
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: az group list

      - name: Terraform Init
        run: |
          cd infra/dev && terraform init

      - name: Terraform Plan
        run: |
          cd infra/dev && terraform plan

      - name: Terraform Apply
        run: |
          cd infra/dev && terraform apply -auto-approve

