name: Azure Deploy

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: "An example input"
        required: true
        default: "test"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: az account show
      - run: az group list

      - name: Terraform Init
        run: |
          cd infra/dev && terraform init

      - name: Terraform Plan
        run: |
          cd infra/dev && export TF_LOG=DEBUG && terraform plan \
            -var "azure_roles=Reader" \
            -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "branches=main" \
            -var "environments=dev,uat,prod" \
            -var "tags=latest" \
            -var "pull_request=true" \
            -var "github_organization_name=Law78" \
            -var "github_repository_name=nextjs15-crash-course"

      - name: Terraform Apply
        run: |
          cd infra/dev && terraform apply -auto-approve

      - name: Remove Terraform Lock
        run: |
          cd infra/dev && rm -f .terraform.lock.hcl
