name: Azure Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          cd infra/dev && terraform init

      - name: Terraform Plan
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          cd infra/dev && terraform plan -no-color -out=tfplan

      - name: Debug Variables
        run: |
          echo "Azure Subscription ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Check tfplan file
        run: |
          ls -l infra/dev/tfplan

      - name: Terraform Apply
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          cd infra/dev && terraform apply -auto-approve tfplan

      - name: Remove Terraform Lock
        run: |
          cd infra/dev && rm -f .terraform.lock.hcl
