name: Azure Deploy

on:
  workflow_dispatch:
    inputs:
      azure_roles:
        description: "Azure roles"
        required: true
        default: '["Reader"]'
      branches:
        description: "Branches"
        required: true
        default: '["main"]'
      environments:
        description: "Environments"
        required: true
        default: '["dev", "uat", "prod"]'
      tags:
        description: "Tags"
        required: true
        default: '["latest"]'
      pull_request:
        description: "Pull request"
        required: true
        default: "true"
      github_organization_name:
        description: "GitHub organization name"
        required: true
        default: "Law78"
      github_repository_name:
        description: "GitHub repository name"
        required: true
        default: "nextjs15-crash-course"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: az account show
      - run: az group list

      - name: Terraform Init
        run: |
          cd infra/dev && terraform init

      - name: Terraform Plan
        run: |
          cd infra/dev && export TF_LOG=DEBUG && terraform plan \
            -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \

      - name: Terraform Apply
        run: |
          cd infra/dev && terraform apply -auto-approve

      - name: Remove Terraform Lock
        run: |
          cd infra/dev && rm -f .terraform.lock.hcl
