name: Deploy to Azure with Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment (DEV or PROD)"
        required: true
        default: "DEV"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 # Sostituisci con la versione di Terraform desiderata

      - name: Change to infra directory
        run: cd infra

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ github.event.inputs.environment == 'PROD' && secrets.PROD_AZURE_CLIENT_ID || secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ github.event.inputs.environment == 'PROD' && secrets.PROD_AZURE_CLIENT_SECRET || secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ github.event.inputs.environment == 'PROD' && secrets.PROD_AZURE_SUBSCRIPTION_ID || secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ github.event.inputs.environment == 'PROD' && secrets.PROD_AZURE_TENANT_ID || secrets.AZURE_TENANT_ID }}

      - name: Cleanup
        run: terraform workspace select default || terraform workspace new default
