name: "Link PR title"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    name: Validate PR title and Check Trello Card
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          cd .github/scripts  # Naviga nella directory dove si trova il package.json
          npm install

      - uses: Slashgear/action-check-pr-title@860e8dc639f8e60335a6f5e8936ba67ed2536890
        id: lint
        with:
          regexp: "\\[#([a-zA-Z]+(-[0-9]+)?|[0-9]+)\\]"
        continue-on-error: true

      - name: Verifica titolo PR su Trello
        run: |
          node .github/scripts/trello.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_AUTH_TOKEN: ${{ secrets.TRELLO_AUTH_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
      - name: Failure message
        if: steps.lint.outcome != 'success'
        run: |
          echo "Pull request title (${{ github.event.pull_request.title }}) is not properly formatted or it is not related to any Trello card"
          exit 1
