name: "Link PR title"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "information"
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: "Purpose of Run This Workflow?"
        required: true
        type: string
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    name: Validate PR title and Check Trello Card
    runs-on: ubuntu-22.04
    env:
      SAMPLE: "^.*sample.*"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          cd .github/scripts  # Naviga nella directory dove si trova il package.json
          npm install

      - uses: Slashgear/action-check-pr-title@860e8dc639f8e60335a6f5e8936ba67ed2536890
        id: lint
        with:
          regexp: "\\\\[(#?[A-Z]*-[0-9]*( |, )?){1,}\\\\]"
        continue-on-error: true

      - name: Verifica titolo PR su Trello
        run: |
          node .github/scripts/trello.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Failure message
        if: steps.lint.outcome != 'success'
        run: |
          echo "Pull request title (${{ github.event.pull_request.title }}) is not properly formatted or it is not related to any Jira issue"
          exit 1
